### ISSUE TITLE
rel_path not properly defined

### ISSUE THREAD

**Issue by jkerenyi** [KIOS-Research/ImportPhotos#105]
In preparing a KML file using ImportPhotos, I discovered that the RelPath property is not being properly defined. This line:

    rel_path = self.selected_folder + os.path.basename(photo_path)

Leaves out any intervening directories between selected_folder and the photo. For example, if the photo is in a subdirectory several layers deep, the intervening folders are omitted due to the use of os.path.basename. I also believe that selected_folder may not be the right starting point for rel_path; it should instead be the folder that the kml file is being written to. 

The obvious solution, to use os.path.relpath, should work in almost all cases; however, for my use case, which is Windows + OneDrive synchronization, there is a path discrepancy between selected_folder and photo_path that renders this solution incomplete.

It is suggested, and I will attempt to find, that the appropriate solution would be to find a relative path between the output file location and the pictures that doesn't rely on os.path.relpath. (Or, stated differently, doesn't require going to root to discern the relative path.) Another potential avenue would be to normalize directories before passing to os.path.relpath.

**Comment by jkerenyi** [comment]
I have a working solution. Once I realized that the path needs to be relative to the output file rather than to the folder containing the pictures, the solution was obvious. I suggest the following line to replace the current line defining rel_path:

    rel_path = os.path.relpath(photo_path,start=os.path.dirname(self.dlg.out.text()))

I tested the revised script and confirmed proper operation.

**Comment by SylvinoBobino** [comment]
Hello, can you please share the revised plug in?

**Comment by jkerenyi** [comment]
Yes of course. I can't attach it to this message because it's not allowed. Please advise how you would like me to transmit it.

**Comment by jkerenyi** [comment]
I forked the project so I could create a pull request. Please review and advise.

**Comment by SylvinoBobino** [comment]
Hi jkereyi does this fix still work for you? It's been a couple months since I've last done it but now when I open the KML file and click the point the viewer is broken and does not display the photo anymore. Just a small question mark in a blue box.

**Comment by Mariosmsk** [comment]
Relative with #114, #112. Check the newest version `ImportPhotos v3.0.6`.
