### ISSUE TITLE
I am puzzled why the bearing/azimuth from my iphone show up as a rational number

### ISSUE THREAD

**Issue by rful011** [KIOS-Research/ImportPhotos#12]
Firstly thanks of a great plugin!  It just works :)
I am however puzzled as to why the bearing in the azimuth field is shown as a ratio of two integers (i.e. as a rational number)  everything else I have used to view the meta data displays it as a decimal.

It is a bit of a pain having to split the string and then convert to integers and perform the devision. At least QGIS allow you to do this on the fly!

**Comment by rful011** [comment]
AH!   found this <https://sno.phy.queensu.ca/~phil/exiftool/TagNames/GPS.html> and as I had suspected this is part of the EXIF standard that decimal numbers are represented as rationals.

Can I suggest that you return the value as a floating point value.  Most other tools that extract exif data do this.   Given that this is a change in behaviour you would probably want to add an option to get the new behaviour.

**Comment by rful011** [comment]
OK, this must be a bug :)   looking at the code I see you have converted all the other numbers to decimal *except* the Direction.

**Comment by chgeorgios** [comment]
Thanks for your comment. We will upload a new version soon for both QGIS 2.x and 3.x.
