### ISSUE TITLE
Error line 438 file ImportPhotos.py

### ISSUE THREAD

**Issue by ubazzicu** [KIOS-Research/ImportPhotos#15]
OS: Windows
QGIS version: 2.18.4

Hello, today the plugin give me this error:

![image](https://user-images.githubusercontent.com/36731070/45877559-91005280-bd9e-11e8-9323-6adb9eda4c35.png)

Someone know how to fix it?
Thank you in advice!

**Comment by Mariosmsk** [comment]
You can download the file: https://raw.githubusercontent.com/KIOS-Research/ImportPhotos/master/ImportPhotos.py

And replace the ImportPhotos.py here: C:\Users\USER\.qgis2\python\plugins\ImportPhotos
Restart QGIS
Test that. Thanks.

**Comment by ubazzicu** [comment]
@Mariosmsk : it works perfectly!

Thank you very much!
