### ISSUE TITLE
Double click to display image stops working after several images

### ISSUE THREAD

**Issue by YenGr** [KIOS-Research/ImportPhotos#17]
I have successfully used Import Photos to display locations of photos within QGIS.

When I double click a location the photo displays correctly. This might happen 3 or 4 times then it stops working and only date and time are displayed.

Closing and re-opening the project doesn't work. If I shutdown and restart QGIS the same thing happens - the first two or three images display then it stops working. The order in which I click images has no effect - always the same symptoms.

I am running QGIS 3.2.3 using ImportPhotos 1.4 (installed via the QGIS Plugins menu). 

Windows 10 with QGIS 32bit on a 64 bit machine.

![image](https://user-images.githubusercontent.com/44333725/47263906-a95abd00-d556-11e8-84f2-2673edc0198c.png)

**Comment by Mariosmsk** [comment]
Check the newest version 1.7. Thanks!

**Comment by YenGr** [comment]
Thanks for the prompt response. Yes it is working well now.

One useful addition to this tool would be the ability to turn on a small symbol when viewing the image at the centre pixel of the image. This would be very useful when attempting to determine where the photo was taken relative to other QGIS features.
