### ISSUE TITLE
Bug: the photo window stays "on top" of everything else

### ISSUE THREAD

**Issue by AlisterH** [KIOS-Research/ImportPhotos#19]
I just tried this plugin in 3.x on Windows.   When using "Click photos", the window displaying the photo is displayed "on top" of all other dialogs and windows, but it is not modal (i.e. you can do other things while it is open).

IMHO you have made the right choice in not making it modal.  But making it always "on top" is very problematic.  

- If a user opens a modal dialog (e.g. Layer>properties) and the photo display is above it, then there is a good chance they won't be able to figure out what is going on, or that they need to press Esc to cancel out of the (invisible) modal dialog before they can move or close the photo display.
- It also stays above other applications, which is not desirable.  If a user needs it to be on top then they can manually achieve that by using a suitable window manager (or whatever special tool is necessary on less capable operating systems).

**Comment by samillar94** [comment]
The import and open dialogs also stay on top. 

(I should say, this plugin is a really neat concept and I'm looking forward to checking it out when I revert to QGIS 3.2.)

**Comment by Mariosmsk** [comment]
We have removed the "stay on top". Check the newest version. Thanks!
