### ISSUE TITLE
Photos not imported.

### ISSUE THREAD

**Issue by Tyrov77** [KIOS-Research/ImportPhotos#22]
When I add a folder with geotagged photos, none of them are imported. 

"No new photos were added." 

The photos have proper location info in the exif data. Using OSX 10.13, Qgis 3, Python 3.6.

**Comment by Tyrov77** [comment]
Thanks for the update. I installed it and now I get this error. 

UnboundLocalError: local variable 'point' referenced before assignment 
Traceback (most recent call last):
  File "/Users/Jorge/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 560, in ok
    del photos, Shp, point, feature, layer
UnboundLocalError: local variable 'point' referenced before assignment

**Comment by reginaldc** [comment]
Same problem here.
I commented out the delete instruction and the plugin continues execution but the result is always no photos were added.
