### ISSUE TITLE
Empty attribute table

### ISSUE THREAD

**Issue by Mariosmsk** [KIOS-Research/ImportPhotos#23]
Not working for the newest version QGIS 3.4

**Comment by samillar94** [comment]
I'm finding the same. There's an empty attribute table if saving as geoJSON, and a table with only an arbitrary FID column if saving as gpkg or shp. 

After import the view pans to the wrong place. The photos are around -6, 54 lat/long, but the plugin navigates to -6, 54 in the project CRS, which in my case is Irish Grid.

**Comment by Mariosmsk** [comment]
fix empty attribute table 94874a1d47001d903c214ae3ccc7edc2824cb699 v1.6

**Comment by brunellop** [comment]
Hi,
Not working for the newest version QGIS 2.18.25, the table does not report the attributes of the photo.

**Comment by Mariosmsk** [comment]
@brunellop, it's ok now. Check the newest version v1.7 from qgis. Thanks!
