### ISSUE TITLE
'ImportPhotos' object has no attribute 'outputPath' 

### ISSUE THREAD

**Issue by Heryx** [KIOS-Research/ImportPhotos#24]
Hi, i have a problem with the puglin, this is the error:
```
AttributeError: 'ImportPhotos' object has no attribute 'outputPath' 
Traceback (most recent call last):
  File "/home/giuseppe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 307, in ok
    lphoto = os.path.basename(self.outputPath)
AttributeError: 'ImportPhotos' object has no attribute 'outputPath'
```
It happens when I click on "browser" to give the path to the folder.

![schermata del 2018-11-02 18-49-50](https://user-images.githubusercontent.com/11267377/47931794-29c2db80-ded0-11e8-9124-4ee428199d3a.png)

**Comment by ekolabynet** [comment]
Me too. I've updated the plugin to the newest version available (1.6) on the qiute stable QGIS  
3.4.1-Madeira. on Kubuntu 18.04. 
Is this the same old bug emerging again or an issue of python etc.?

**Comment by ekolabynet** [comment]
The text of my error:

> Wystąpił błąd podczas wykonywania kodu Pythona: 

AttributeError: 'ImportPhotos' object has no attribute 'extension' 
Traceback (most recent call last):
  File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 323, in ok
    self.extension = '.'+self.extension.split()[-1][2:-1].lower()
AttributeError: 'ImportPhotos' object has no attribute 'extension'


Wersja Pythona: 3.6.6 (default, Sep 12 2018, 18:26:19) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] 
Wersja QGIS: 3.4.1-Madeira Madeira, 383851c 

Lokalizacja Pythona:
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/AreaAlongVector
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/networks
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pdaltools
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geomovetools
/usr/share/qgis/python
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/piotr/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SwapVectorDirection
.
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QuickMultiAttributeEdit3/forms
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor
/usr/lib/python3/dist-packages/IPython/extensions
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/forms
/media/piotr/DATA/APPL/APPL_Skanska/Jasminowa/FTP/Monitoring/GIS/Projekty

**Comment by Mariosmsk** [comment]
@Heryx, @ekolabynet, you can check the newest version. I hope it's ok. Thanks!

**Comment by alexmodesto73** [comment]
Error  


Une erreur est survenue lors de l'éxécution du code Python: 

KeyError: '.apefil' 
Traceback (most recent call last):
  File "/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos-master/ImportPhotos.py", line 581, in ok
    self.extension = self.extension_switch[self.extension]
KeyError: '.apefil'


Version de Python : 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516] 
Version de QGIS : 3.4.1-Madeira Madeira, 383851c 

Chemin Python :
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/extlibs
/usr/share/qgis/python
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Beeline/libs
.
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs
/home/alex/Documents/perso
