### ISSUE TITLE
Suggestion: drop support for QGIS 2.x

### ISSUE THREAD

**Issue by volcan01010** [KIOS-Research/ImportPhotos#26]
I would consider dropping support for QGIS 2.x in this plugin.  Now that QGIS 3.4 has been released as a long-term support version, the number of users using QGIS 2.x is going to decrease quickly.  

Supporting QGIS 2.x adds a lot of extra complexity to the code and provides many places for bugs to hide.  It also means that you cannot take advantage of Python 3 features such as `pathlib`, which can greatly simplify the handling of file locations.  You also have to be much more careful about text string encodings.

I think that there are metadata flags that would stop someone installing the plugin on QGIS 2.x.  In the plugin documentation you could suggest that they use the [Geotag and Import Photos](https://plugins.qgis.org/plugins/geotagphotos/) and [eVis](https://biodiversityinformatics.amnh.org/open_source/evis/documentation.php) plugins instead.  That solution works reasonably well.

**Comment by Mariosmsk** [comment]
Thanks for the suggestion. Most probably, all the future updates will address QGIS, 3.x. Also, thanks for the suggestion to use the `pathlib`, we will use it in a future version.
