### ISSUE TITLE
DateTime attributes: when photo modified not taken

### ISSUE THREAD

**Issue by kevgriff** [KIOS-Research/ImportPhotos#30]
Thank you for providing such a useful add-in.

I have an issue with the Date and Time attributes in the geoJSON point file. They appear to show when the photo was modified by my photo editing software and not the when I took the photo (see attachment).

![exif_data](https://user-images.githubusercontent.com/45494509/49304960-bd82ca00-f4c5-11e8-94d4-217c92f7521b.jpg)

May I suggest you use the EXIF Create Date as the data source?

Best wishes,

Kevin.

**Comment by Mariosmsk** [comment]
Thanks @kevgriff, 

Soon there will be a new stable release with new features and fixes. If you want to try the version [ImportPhotos v1.8](https://github.com/KIOS-Research/ImportPhotos/tree/v.1.8) before we send for the update. 

Thanks.
Marios

**Comment by Mariosmsk** [comment]
You can download the [ImportPhotos v1.8](https://github.com/KIOS-Research/ImportPhotos/archive/v.1.8.zip). 
1. Unzip the file ImportPhotos
2. Replace the folder ImportPhotos in path C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
3. Restart QGIS desktop.

**Comment by kevgriff** [comment]
I have tested it and it works well. Thank you.
I have found something else I would like to raise. I will start a new issue.
Thanks,
Kevin.

**Comment by Mariosmsk** [comment]
Ok, feel free to make a new issue in order to close that one.
