### ISSUE TITLE
Photo sort sequence

### ISSUE THREAD

**Issue by kevgriff** [KIOS-Research/ImportPhotos#31]
Marios,

The photos in the attribute table appear to be in no particular sequence. I would like them to be in chronological sequence so that when I am browsing they appear in the order in which I took them. May I suggest sorting them by date/time before outputting the records.

Thanks,

Kevin.

**Comment by Mariosmsk** [comment]
Solved this issue in version 1.8
Thanks

**Comment by kevgriff** [comment]
Thank you, Marios.
Kevin.
