### ISSUE TITLE
Black rectangles on both sides of imported photos

### ISSUE THREAD

**Issue by TheGrave** [KIOS-Research/ImportPhotos#36]
Something weird happens when I import photos (on all of them), see this link:: 

https://mega.nz/#!Rdt12YIC!l5H1OvtgJQmTXiVieMzFZXOIgJDeGapLY7QPY5UKmc4

Original photo:

https://mega.nz/#!UIsBTaJK!hXuOi1_bqZUnq02eqkHG_PGI572iJPjhGRP66pUudG0

QGIS version: 3.4.4
Plugin version: 1.8
OS: Lubuntu 18.04 x64

**Comment by Mariosmsk** [comment]
Hi @TheGrave ,
`ImportPhotos v1.9` has been released. Check QGIS repository.
Thanks.

**Comment by TheGrave** [comment]
Now it's worse, I can't import a single geotagged photo :) No error displayed, just:
 "Import completed"

"Details:
   No new photos were added."

All my photos are geotagged.
