### ISSUE TITLE
version 1.7 is missing in Pluginmanager @QGIS >= 2.18.25

### ISSUE THREAD

**Issue by rdbath** [KIOS-Research/ImportPhotos#38]
Version 1.7 has set 2.18.25 as Minimum QGIS version.
QGIS plugin-manager does not check the minor-versions, as it calls 
https://plugins.qgis.org/plugins/plugins.xml?qgis=2.18

So QGIS 2.18 user will not be able to update to version 1.7 through the QGIS plugin-manager even if they use QGIS versions >=2.18.25

**Comment by Mariosmsk** [comment]
We dropped support for QGIS 2. Thanks.
