### ISSUE TITLE
"UserLabel" attribute not imported

### ISSUE THREAD

**Issue by gjsa73** [KIOS-Research/ImportPhotos#39]
"UserComment" attribute is not imported
This is important because it records any comments added to EXIF data when in the field.

Attachment below is a modification made to the QGIS 2 photoimporter plugin to import this attribute.

[photoimporter.py.txt](https://github.com/KIOS-Research/ImportPhotos/files/2863568/photoimporter.py.txt)

**Comment by Mariosmsk** [comment]
Hi @gjsa73,
`ImportPhotos v1.9` has been released. Check QGIS repository.
Thanks.
