### ISSUE TITLE
How to install necessary module on Linux?

### ISSUE THREAD

**Issue by queenmedley** [KIOS-Research/ImportPhotos#40]
I use Archlinux and Qgis verion is 3.4.
Plugin was installed well without error, but problem is it donesn't make output.
I read the readme and found that there are some modules needed, especillay pil module.
But pip can't find the pil module. 
How to get the module?

**Comment by Mariosmsk** [comment]
Hi @queenmedley,
`ImportPhotos v2.0` has been released. Check QGIS repository.
Thanks.
