### ISSUE TITLE
"No new photos were added"

### ISSUE THREAD

**Issue by DrArn** [KIOS-Research/ImportPhotos#41]
Hi
I am running the newest plugin version in QGIS 3.4.4 under Linux Mint 19.
Even though the directories I choose contain geotagged images (from a drone) that have been successfully imported before, I now only get the "No new photos were added" and nothing else.
I tried different outputs and reinstalling in the extensions manage and from zip with no success.
any advice?
Greetings
Arn

**Comment by Mariosmsk** [comment]
Hi @DrArn,
`ImportPhotos v2.0` has been released. Check QGIS repository.
Thanks.

**Comment by gHupf** [comment]
Hi!

I get the same error as described by @DrArn on Windows 10 with QGIS version 3.4.x using `ImportPhotos v2.0`.

The old version `ImportPhotos v1.9` works perfectly well if I use QGIS version 3.4.4 or 3.4.5.

Greetings

**Comment by Mariosmsk** [comment]
Check out the updated version `ImportPhotos v2.1` . Thanks.

**Comment by davdent** [comment]
I am getting the same issue using v. 3.0.3 and QGIS 3.10 under Ubuntu. I get the message "Import complete. Details: no new photos were added." 

Any idea what is wrong and how I can fix it?

**Comment by Simone-Brotto** [comment]
I am getting the same issue using v. 3.0.3 and QGIS 3.22.3 under WIN10.
I get the message "Import complete. Details: no new photos were added."
