### ISSUE TITLE
Please install python module "exifread" or "PIL"

### ISSUE THREAD

**Issue by samillar94** [KIOS-Research/ImportPhotos#51]
Hi,

I downloaded ImportPhotos today from the repository in QGIS3.6 on OSGeo4W on Windows 10.

I get the error message above. I installed Exiftools as per the method [here](https://gis.stackexchange.com/questions/193164/installing-exifread-module-into-qgis-2-14/248353) and restarted QGIS but still get the same error message.

I checked out issues #10 and #16 and tried `import pip; pip.main(['install', 'exifread']);` and got `ModuleNotFoundError: No module named 'pip'`.

I am curious as to why exiftools cannot simply be included in the plugin. The photo2shape plugin was the same except the method in the link above worked for it.

Many thanks
Sam

**Comment by Mariosmsk** [comment]
Hi @samillar94 , check in the folder of `ImportPhotos` `(C:\Users\USERNAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ImportPhotos)` to find the file `install_pip_packages.bat` do it double click on this. Let me know if it works. Restart QGIS.

Thanks,
Marios

**Comment by samillar94** [comment]
Hi Marios,

Thanks for your reply. The installation failed:

`C:\Users\☺\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ImportPhotos>cd /d C:\Users\☺\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ImportPhotos\

C:\Users\☺\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ImportPhotos>call "py3-env.bat"
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Collecting exifread (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7b/cb/92b644626830115910cf2b36d3dfa600adbec86dff3207a7de3bfd6c6a60/ExifRead-2.1.2.tar.gz
Collecting pillow (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/40/f2/a424d4d5dd6aa8c26636969decbb3da1c01286d344e71429b1d648bccb64/Pillow-6.0.0-cp37-cp37m-win_amd64.whl
Installing collected packages: exifread, pillow
  Running setup.py install for exifread ... error
    Complete output from command "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\☺\\AppData\\Local\\Temp\\pip-install-8tumqn5p\\exifread\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\☺\AppData\Local\Temp\pip-record-goezu_12\install-record.txt --single-version-externally-managed --compile:
    Warning: 'classifiers' should be a list, got type 'tuple'
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\exifread
    copying exifread\classes.py -> build\lib\exifread
    copying exifread\exif_log.py -> build\lib\exifread
    copying exifread\utils.py -> build\lib\exifread
    copying exifread\__init__.py -> build\lib\exifread
    creating build\lib\exifread\tags
    copying exifread\tags\exif.py -> build\lib\exifread\tags
    copying exifread\tags\__init__.py -> build\lib\exifread\tags
    creating build\lib\exifread\tags\makernote
    copying exifread\tags\makernote\apple.py -> build\lib\exifread\tags\makernote
    copying exifread\tags\makernote\canon.py -> build\lib\exifread\tags\makernote
    copying exifread\tags\makernote\casio.py -> build\lib\exifread\tags\makernote
    copying exifread\tags\makernote\fujifilm.py -> build\lib\exifread\tags\makernote
    copying exifread\tags\makernote\nikon.py -> build\lib\exifread\tags\makernote
    copying exifread\tags\makernote\olympus.py -> build\lib\exifread\tags\makernote
    copying exifread\tags\makernote\__init__.py -> build\lib\exifread\tags\makernote
    running build_scripts
    creating build\scripts-3.7
    copying and adjusting EXIF.py -> build\scripts-3.7
    running install_lib
    creating C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\exifread
    error: could not create 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\exifread': Access is denied

    ----------------------------------------
Command ""C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\☺\\AppData\\Local\\Temp\\pip-install-8tumqn5p\\exifread\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\☺\AppData\Local\Temp\pip-record-goezu_12\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\☺\AppData\Local\Temp\pip-install-8tumqn5p\exifread\
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Press any key to continue . . .`

Should I edit setup.py to point to a folder it has write permission to?

Sam

**Comment by Mariosmsk** [comment]
Open cmd.exe

- `cd C:\Program Files\QGIS 3.6\bin`
- `python3 -m pip install exifread`

check this

**Comment by samillar94** [comment]
Thanks -

```
C:\Users\samil>cd C:\Program Files\QGIS 3.6\bin
The system cannot find the path specified.

C:\Users\samil>cd C:\OSGeo4W64\bin

C:\OSGeo4W64\bin>python3 -m pip install exifread
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00003704 (most recent call first):
```

It just ends like that. As you can see I switched to the OSGeo4W bin folder where python3 is installed. (`C:\OSGeo4W64\apps\qgis\bin` has only qgis files.)

**Comment by Mariosmsk** [comment]
I forget to say run `install_pip_packages.bat` Run as Administrator

https://www.youtube.com/watch?time_continue=141&v=IO7Psv65WUs

**Comment by samillar94** [comment]
Nothing doing.

I also followed the instructions on the video using `set "input=C:\OSGeo4W64"` in `pip_install_packkages.bat` from Dropbox with no luck. The cmd window appears briefly and disappears.

**Comment by samillar94** [comment]
Hi, I should have asked - have you designed this to be able to work with OSGeo4W advanced installation, i.e. where multiple versions of QGIS may be installed in an OSGeo4W folder rather than one in Program Files/QGIS n.x? If so where do I need to install exifread? Many thanks

**Comment by GitMorin** [comment]
I have the same problem. Has anyone solved it?
When  run install_pip_packages i get (as admin)

```
The system cannot find the path specified.
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting exifread (from -r requirements.txt (line 1))
```

I have installed exifread and Pillow with pip install myself. But clearly not to the right env as I canot import it in the QGIS python console. I have installed QGIS through OSGeo4W advanced

**Comment by GitMorin** [comment]
I was successful to install 3rd party modules for an installation based from OSGeo4W advanced installation following the tutorial below.
https://www.youtube.com/watch?v=94W51WuDKzA
