### ISSUE TITLE
Viewer not showing up

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [KIOS-Research/ImportPhotos#53]
Import of photos worked (with some quirks I will replicate later), a shape file was populated.
But the "Viewer"-button remains without a function. I get a white cross as selector, but clicking on the symbols does not do anything. Hovering over just reveals the ID from the attribute table.

QGIS 3.8.0 on Linux Mint 19.1

**Comment by Bernd-Vogelgesang** [comment]
updated to the latest version. Viewer still not functional.

**Comment by jsgoodall** [comment]
Am having the same problem with v 2.2.2 ( installed from zip) and QGIS 3.8. It worked before but can't remember what updated and broke it, very inconvenient.

I can import photos ok, I can select them with select feature and then see the photo that should be shown. But when I do it the right way by "Click Photos" the white cross does nothing.

Tell me please where should I look for debugging info that might help, thanks!!
