### ISSUE TITLE
Same location photos show only one symbol.

### ISSUE THREAD

**Issue by queenmedley** [KIOS-Research/ImportPhotos#63]
When I take a picture from the same location, only one symbol is displayed on map.
And When "click photo", only one of several pictures will be displayed, and if I press the "show next photo" button, it will randomly move to another location.
I am curious about the order of "show next photo".
I think "show next photo" would be better to show a picture of the same place first and then move on to the next location.
Or better to show only clicked photo (including same location photo).

**Comment by jsgoodall** [comment]
I agree as I have had the same issue when taking pictures of land cover from the same point pointing N, E, W and S or just various azimuths. Maybe the NEXT/PREVIOUS algorithm should contemplate nearness to the picture ( Sort by Distance first, then next sort criteria).

**Comment by chgeorgios** [comment]
This will be fixed in our next release with the option to display the next photo based on the timestamp or location.
