### ISSUE TITLE
failure to load pictures

### ISSUE THREAD

**Issue by rjdini** [KIOS-Research/ImportPhotos#71]
Linux Ubuntu 18 and QGIS 3.12.3

I am unable to load images.   I see from the issues below that others have experienced the same problem.  Could you please give advice??
thanks

2020-06-10T12:39:15     WARNING    Traceback (most recent call last):
              File "/home/rjd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 388, in ok
              self.import_photos(self.directoryPhotos, self.outputPath, self.load_style, showMessageHide)
              File "/home/rjd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 456, in import_photos
              self.extension = self.extension_switch[self.extension]
             KeyError: '.pefi'

**Comment by Gui0delp** [comment]
Hey ! I got the same problems when i want to import photos. If i want to import just one photo it work.

I test on:
QGIS 3.10.7-A Coruña
Plugin version: 2.2.2

OS:
macOS Catalina 10.15
Ubuntu 20.04.1 LTS
Windows 10

Always same problem.

**Comment by Gui0delp** [comment]
Hi ! Maybe the same problem described here #65 

Kind regards

**Comment by chgeorgios** [comment]
We are working on resolving this issue. In the midtime, you can use Import Geotagged Photos to upload the photos and you can use the "Click Photos" plugin of the import photos to open the images.
