### ISSUE TITLE
Issue in import jpg

### ISSUE THREAD

**Issue by NicolaPx** [KIOS-Research/ImportPhotos#72]
During an import session the following error message appears:
2020-10-03T13:49:24     WARNING    Traceback (most recent call last):
              File "/home/nicola/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 388, in ok
              self.import_photos(self.directoryPhotos, self.outputPath, self.load_style, showMessageHide)
              File "/home/nicola/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 456, in import_photos
              self.extension = self.extension_switch[self.extension]
             KeyError: '.pefi'

**Comment by Gui0delp** [comment]
Hi ! Maybe the same problem described here #71

**Comment by Bernd-Vogelgesang** [comment]
Seems the developers lost their github account password: Last reaction on an issue August 2019!
If you only want to import images to create an associated point file, at have a look at the built-in toolbox function "import geotagged photos"
Examples here:https://communityhealthmaps.nlm.nih.gov/2019/02/21/mapping-field-photos-in-qgis/

**Comment by Gui0delp** [comment]
@Bernd-Vogelgesang Yes it sounds like it ... Thank you for the information, have a nice day !

**Comment by chgeorgios** [comment]
Hi, give us some time and we will look into it.

**Comment by chgeorgios** [comment]
In the midtime, you can use Import Geotagged Photos to upload the photos and you can use the "Click Photos" button of the Import Photos plugin to view the images.

**Comment by Bernd-Vogelgesang** [comment]
Nope, we can't. "Click Photos" is also non-functional on Linux, see https://github.com/KIOS-Research/ImportPhotos/issues/53
