### ISSUE TITLE
The directory to access the photos is changed

### ISSUE THREAD

**Issue by Pacomerpaella** [KIOS-Research/ImportPhotos#84]
I can't open the photos in QGIS because the path where the photos are saved is
C: / Users / pacom / OneDrive / Desktop / Fotos_puentes \ IMG_1332.jpg
and when I click on the link, the web browser opens
c / Users / pacom / OneDrive / Desktop / Fotos_puentes% 5CIMG_1332.jpg

Greetings

**Comment by Mariosmsk** [comment]
Hi @Pacomerpaella, please check out the latest version of ImportPhotos v3.0.5!
Thanks
