### ISSUE TITLE
plugin does not import photos

### ISSUE THREAD

**Issue by davdent** [KIOS-Research/ImportPhotos#85]
When I try to import photos using the plugin, I get the message: Import completed. Details: No new photos were added. Note that these are geotagged images that I have been able to import using QGIS's core tool Import Geotagged Photos. I am using QGIS 3.10 under Ubuntu 21.10. The ImportPhotos plugin is v. 3.0.3.

![Screenshot from 2022-01-15 09-18-20](https://user-images.githubusercontent.com/52795711/149625119-aeea0c6d-ab32-496d-afee-08fb1e174bd0.png)

**Comment by Mariosmsk** [comment]
Thanks @jfbourdon !
