### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by IsabelleGiraud** [KIOS-Research/ImportPhotos#86]
Hi

I have an issue with Import Photo with Qgis 3.4.5 and the new version 3.0.3.
It was fine with the 2.2.2 version but now I have an error message

After I have chosen the folder and the file name and click OK, nothing append.
The new file is created but does not open automatically.
When I drag and drop it into Qgis and try to use the Click Photo tool, I have and error message

2022-01-21T15:21:23     WARNING    Traceback (most recent call last):
              File "C:/Users/isabelle.giraud/AppData/Roaming/QGIS/QGIS3\profiles\PRNT/python/plugins\ImportPhotos\ImportPhotos.py", line 276, in setMouseClickMapTool
              if layer.type() == QgsMapLayerType.VectorLayer and layer.fields().names() == FIELDS:
             NameError: name 'QgsMapLayerType' is not defined

Thanks for your help

**Comment by Mariosmsk** [comment]
Hi @IsabelleGiraud, please check out the latest version of ImportPhotos v3.0.5!
Thanks
