### ISSUE TITLE
Error while importing new

### ISSUE THREAD

**Issue by FlyingEagle** [KIOS-Research/ImportPhotos#88]
It seemded that I have one or more photos with corrupt data in azimuth, it seemed to be "".

Now the Plugin is crashing QGIS!!!

Message: Layer: Could not store attribute "Azimuth": Could not convert value "" to target type.

It would be nice to see the actual used photo / filename, the error message should have the filename, too.
I can not found anything in QGIS log because QGIS crashed. (It happened all the time, I use the latest versions of QGIS and plugin!).
After reloading QGIS and opening the shape-file-ouput I can see photos there, but I can not find out how many photos are imported and how many not.

**Comment by Mariosmsk** [comment]
Hi @FlyingEagle, please check out the latest version of ImportPhotos v3.0.5!
Thanks
