### ISSUE TITLE
error importing 

### ISSUE THREAD

**Issue by matematto** [KIOS-Research/ImportPhotos#89]
I try to translate the message:

unable to store attribute "Date": Unable to convert value "" to destination type 

QGIS (3.22.3 Import Photo updated ) freezes and I have to force reload
PS photos are taken with the same devices when all worked fine
![import photo](https://user-images.githubusercontent.com/66550812/154029844-d6eb0f9d-557d-43f9-a571-afa2decd7e16.png)

**Comment by gaspermeister** [comment]
I had the same issue and managed to solve it by correcting the “ImportPhotos.py” file in the plugin folder (I am using ImportPhotos v 3.0.4). I made the following changes:
– line 632 from: date = '' to:  date = None
– line 633 from: time_ = '' to:  time_ = None
– line 634 from:  timestamp = ''  to:  timestamp = None 

I also experienced a similar error regarding the Azimuth attribute field and made similar corrections to lines 641 and 643.

**Comment by Mariosmsk** [comment]
Hi @matematto thanks to create the issue and @gaspermeister for the solution suggestion. Please check out the latest version of ImportPhotos v3.0.5!
