### ISSUE TITLE
A mouse click on a photo crashes when you change location of project (appeared on Ubuntu 20.04)

### ISSUE THREAD

**Issue by turzik-x** [KIOS-Research/ImportPhotos#90]
https://github.com/KIOS-Research/ImportPhotos/blob/0c5ec7e9216ad36767c9f1e9f2aec43b46758d45/code/MouseClick.py#L103

I suggest this fix:
imPath = os.path.join(QFileInfo(**self**.prj.fileName()).absolutePath(), feature.attributes()[feature.fieldNameIndex('RelPath')])

**Comment by Mariosmsk** [comment]
Hi @turzik-x and thanks for your suggestion, please check out the updated version ImportPhotos v3.0.5!
