### ISSUE TITLE
QGIS Actions and Tooltip

### ISSUE THREAD

**Issue by Fabien98** [KIOS-Research/ImportPhotos#95]
In addition to the nice photo viewer, would it be possible when the layer is created to automatically create in the layer default properties:

- A tooltip where the user can see the pictures thanks to HTML formatting:
Example of the tooltip:
```
==============================================<br>
<div style="width:400;height:500">
<b>[% "Name of the file" %]</b><br>
<body>
<img src="[% "image" %]" alt="Missing picture" width="400" height="300" />
</body>
</div>
```

- A default action which open the photo with the default viewer

**Comment by Mariosmsk** [comment]
Hi @Fabien98 , please check out the updated version ImportPhotos v3.0.5! 
Thank you for your suggestion!
