### ISSUE TITLE
error is thrown if file in Path field not exists

### ISSUE THREAD

**Issue by KrisRadowski** [KIOS-Research/ImportPhotos#97]
Hello,

When file specified in Path field doesn't exists; an error is thrown:
![Zrzut ekranu 2022-10-25 091729](https://user-images.githubusercontent.com/10513413/197708726-2babe343-2531-4e0b-8eaa-505e4eaec60f.png)

I decided to fork this project and fixed it already in my fork, please let me create a pull request.

Sincerely,
K.R.

**Comment by Mariosmsk** [comment]
Thanks @KrisRadowski! Please check out the updated version ImportPhotos v3.0.5!
